### ISSUE TITLE
throw new TypeError('Request path contains unescaped characters.');

### ISSUE THREAD

**Issue by RobQuads** [SalesforceEng/global-tunnel#13]
Without the global-tunnel my code connects directly to the endpoint fine but when I enable global-tunnel via a MockServer proxy then I am getting the following error:

_http_client.js:54
    throw new TypeError('Request path contains unescaped characters.');
    ^

TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:54:11)
    at TunnelingAgent.exports.request (http.js:31:10)
    at TunnelingAgent.createSocket (/home/test/NodeApps/node_modules/global-tunnel/node_modules/tunnel/lib/tunnel.js:116:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/home/test/NodeApps/node_modules/global-tunnel/node_modules/tunnel/lib/tunnel.js:188:41)
    at TunnelingAgent.addRequest (/home/test/NodeApps/node_modules/global-tunnel/node_modules/tunnel/lib/tunnel.js:80:8)
    at new ClientRequest (_http_client.js:139:16)
    at Object.exports.request (http.js:31:10)
    at Object.globalTunnel._defaultedAgentRequest (/home/test/NodeApps/node_modules/global-tunnel/index.js:211:38)
    at Object.exports.request (https.js:173:15)
    at Object.globalTunnel._defaultedAgentRequest (/home/test/NodeApps/node_modules/global-tunnel/index.js:211:38)

**Comment by bbence84** [comment]
Same here. Any suggestions?

**Comment by simonbernard** [comment]
I had the same problem and raised an issue to `node-tunnel`.
https://github.com/koichik/node-tunnel/issues/12

It seems that dependency to `node-tunnel` should be updated to '0.0.4`.

**Comment by chriskea** [comment]
Same issue, the fix mentioned above resolved it.
